# Generated by Django 5.2 on 2025-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_plub',
            new_name='data_pub',
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.URLField(max_length=100, verbose_name='Site da editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço do livro'),
        ),
    ]
